repos:
- repo: local
  hooks:
    - id: isort
      name: isort
      entry: isort
      stages: [commit]
      language: system
      files: \.py$
    - id: black
      name: black
      entry: black
      stages: [commit]
      args: [--config=pyproject.toml]
      language: system
      files: \.py$
    - id: flake8
      name: flake8
      entry: flake8
      stages: [commit]
      args: [--config=.flake8]
      language: system
      files: \.py$
    - id: mypy
      name: mypy
      entry: mypy
      stages: [commit]
      language: system
      files: \.py$
