[tool.black]
line-length = 119
skip-string-normalization = true
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | dist
)/
'''

[tool.isort]
line_length = 119
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true


[tool.mypy]
exclude = "thirdparty"

